"""Constants for the Canadian Hydrographic Service (CHS) Water Level Web Services integration."""

DOMAIN = "chs_tides"

CONF_LANGUAGE = "language"
CONF_STATION_CODE = "station"
DEFAULT_LANGUAGE = "English"
DEFAULT_SCAN_INTERVAL = "60"
DEFAULT_UNIT_OF_MEASUREMENT = "Feet"

ATTR_HHWMT = "higher_high_water_mean_tide"
ATTR_HWL = "high_water_level"
ATTR_HAT = "highest_astronomical_tide"
ATTR_LLWLT = "lower_low_water_large_tide"
ATTR_HHWLT = "higher_high_water_large_tide"
ATTR_HRWL = "highest_recorded_water_level"
ATTR_LRWL = "lowest_recorded_water_level"
ATTR_MWL = "mean_water_level"
ATTR_LWL = "low_water_level"
ATTR_LAT = "lowest_astronomical_tide"
ATTR_LLWMT = "lower_low_water_mean_tide"
ATTR_GLCMM = "great_lakes_coordinated_monthly_mean"
ATTR_NTHWL = "non-tidal_high_water_level"